"""empty message

Revision ID: 16a5fd11721a
Revises: 
Create Date: 2025-03-20 13:16:07.667804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a5fd11721a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lusername', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['lusername'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('lusername')

    # ### end Alembic commands ###
